// The brand files must exist, be the right size, and be wired into index.html and
// the manifest under the /spellingbee/ base. They are generated by
// design/harness/build-brand-assets.mjs and committed, so nothing else would notice
// a missing or stale one.
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const pub = (f) => resolve("public", f);
const html = readFileSync(resolve("index.html"), "utf8");
const manifest = JSON.parse(readFileSync(pub("manifest.webmanifest"), "utf8"));

function pngSize(file) {
  const b = readFileSync(file);
  expect(b.subarray(1, 4).toString()).toBe("PNG");
  return [b.readUInt32BE(16), b.readUInt32BE(20)];
}

describe("brand assets", () => {
  it("manifest names the game and stays inside the deployed path", () => {
    expect(manifest.name).toBe("Spelling Bee");
    expect(manifest.short_name).toBe("Spelling Bee");
    expect(manifest.start_url).toBe("/spellingbee/");
    expect(manifest.scope).toBe("/spellingbee/");
    expect(manifest.display).toBe("standalone");
  });

  it("every manifest icon exists at its declared size, and one is maskable", () => {
    for (const icon of manifest.icons) {
      expect(existsSync(pub(icon.src))).toBe(true);
      const [w, h] = icon.sizes.split("x").map(Number);
      expect(pngSize(pub(icon.src))).toEqual([w, h]);
    }
    expect(manifest.icons.some((i) => i.purpose === "maskable")).toBe(true);
  });

  it("the favicon, touch icon and share card exist at the right sizes", () => {
    expect(readFileSync(pub("favicon.svg"), "utf8")).toContain("<svg");
    expect(pngSize(pub("favicon-32.png"))).toEqual([32, 32]);
    expect(pngSize(pub("apple-touch-icon.png"))).toEqual([180, 180]);
    expect(pngSize(pub("og-card.png"))).toEqual([1200, 630]);
  });

  it("index.html links them all and carries matching share tags", () => {
    for (const href of ["/favicon.svg", "/favicon-32.png", "/apple-touch-icon.png", "/manifest.webmanifest"]) {
      expect(html).toContain(`href="${href}"`);
    }
    expect(html).toContain('name="theme-color" content="#16130f"');
    expect(manifest.theme_color).toBe("#16130f");
    for (const tag of ['property="og:title" content="Spelling Bee"', 'name="twitter:card" content="summary_large_image"', 'property="og:image:width" content="1200"']) {
      expect(html).toContain(tag);
    }
    // share crawlers need an absolute URL, and it must be under the deployed base
    expect(html).toMatch(/property="og:image" content="https:\/\/iangopen\.github\.io\/spellingbee\/og-card\.png"/);
  });

  it("the favicon is not a plain hexagon (the audit's closest overlap with another game's imagery)", () => {
    const svg = readFileSync(pub("favicon.svg"), "utf8");
    expect(svg).toContain("clipPath"); // the bee, not just an outline
    expect(svg.match(/<path/g).length).toBeGreaterThan(10);
    expect(svg).not.toMatch(/<polygon/);
  });

  it("no Vite scaffold files ship", () => {
    for (const f of ["src/assets/hero.png", "src/assets/react.svg", "src/assets/vite.svg", "public/icons.svg"]) {
      expect(existsSync(resolve(f))).toBe(false);
    }
  });
});
