// Emit lucide glyphs (the icon set the app already ships, ISC licence) as
// inline <svg> strings for the static prototypes, so they need no CDN and add
// no dependency. Output: design/prototypes/_shared/icons.js
//   node design/harness/icons.mjs
import { writeFileSync, mkdirSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { resolve } from "node:path";

const NAMES = [
  "volume-2", "settings", "arrow-left", "user", "users", "trophy", "rotate-ccw",
  "timer", "eye-off", "crown", "heart", "check", "x", "mic", "bell", "share-2", "flame",
];
const out = {};
for (const n of NAMES) {
  const mod = await import(pathToFileURL(resolve(`node_modules/lucide-react/dist/esm/icons/${n}.mjs`)).href);
  const inner = mod.__iconNode
    .map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).filter(([k]) => k !== "key").map(([k, v]) => `${k}="${v}"`).join(" ")}/>`)
    .join("");
  out[n] = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${inner}</svg>`;
}
mkdirSync("design/prototypes/_shared", { recursive: true });
writeFileSync(
  "design/prototypes/_shared/icons.js",
  "// Lucide icons (ISC licence, https://lucide.dev), generated by design/harness/icons.mjs.\n" +
    "// Replaces every <i data-icon=\"name\"></i> with the inline glyph.\n" +
    `const ICONS = ${JSON.stringify(out, null, 0)};\n` +
    `document.querySelectorAll("i[data-icon]").forEach((el) => { el.outerHTML = ICONS[el.dataset.icon] ?? ""; });\n`
);
console.log(`wrote ${NAMES.length} icons`);
